### PR TITLE
Added t1 map

### PR DESCRIPTION
**Pull request by stevedaxiao**
Changed the description and the commit message

### CODE REVIEW

**Comment by fedorov** [comment]
I un-merged your pull request after realizing your commit messages. Please use accurate and descriptive commit message. In this pull request you have 3 commits, all of which have the same "ENH: added T1 Map(ping)". You can also squash your commit messages and have just one commit.

As discussed last time on the call, you need to follow the style rules specified in  http://wiki.slicer.org/slicerWiki/index.php/Documentation/4.4/Developers/Style_Guide#Commits are followed. We discussed this at the last call. I am not sure how to make this more clear than in the guidelines provided at that page.

Also, as discussed before, I strongly recommend you take the time to go over some freely available git courses. Here's one source: https://training.github.com/classes/, another one: https://www.codeschool.com/courses/try-git.

Pinging @pieper in case he has any other suggestions.

**Comment by stevedaxiao** [comment]
What commit message shall I need use?
I just follow the previous commit message 
"ENH: added constant BAT"
Since both are similar.
I can use "ENH: added T1 map as an optional input"
Any thoughts?
I guess I need commit everything again using the new message? But not sure if Github will continue these existed even deleted or closed pull request. This is why you see these 3 consecutive commits in this pull request.

**Comment by fedorov** [comment]
> What commit message shall I need use?

Here is what the instructions say: "A good commit message title (first line) should explain what the commit does for the user, not how it is done. How can be explained in the body of the commit message (if looking at the code of the commit is not self explanatory enough)."

First commit message is ok, I guess. But after that you have 2 more commits with the message "ENH: added T1 Map". These messages have nothing to do with the essence of the change, since what you did is you renamed a variable. Here's an example of one commit that maybe explains this better: "STYLE: rename variables for consistency". Hope this helps.

To clarify, you can you use any development practices for the code you develop on your own or for your lab. But in this situation you are committing to a community repository and you must comply with the rules adopted by the community developing that software.

**Comment by pieper** [comment]
Hi Xiao -

To elaborate on Andrey's points, we often think of the commit message like
an email to future developers.  You want to give them a quick understanding
of what this commit does without requiring them to read through the code.

This is why the 'subject line' of the commit message is important as a
summary, and why the body is sometimes more detailed (a brief note or
single line is fine if there are not many changes).

Best,
Steve

**Comment by stevedaxiao** [comment]
Thank you for your suggestion. I sincerely appreciate it.
But I feel a little bit confused right now. So sorry about that.
At the beginning, because the latest commit is "ENH: added BAT", I think it could be similar and I used "ENH: add T1 Map" or "ENH: add T1 Mapping". But by accidentally I committed 2 more times probably, and once again accidentally something unexpected was written to my code which lead to failure of compile. And as Andriy suggested, I squeezed all my previous commits and finalize the message to "ENH: add T1 Map as an optional input". I think it should be OK.  At least, when I checked git log, it only showed "ENH: add T1 Map as an optional input", the final one I used.
I completely understand the rule and try to make everything the best.
Thank you again.

Best,

Xiao

**Pull request merged**
